//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EXTERNALSERVICE_REQ", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AccountService.EXTERNALSERVICE_RES))]
    public partial class EXTERNALSERVICE_REQ : object
    {
        
        private AccountService.FCUBS_BODY FCUBS_BODYField;
        
        private AccountService.FCUBS_HEADER FCUBS_HEADERField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.FCUBS_BODY FCUBS_BODY
        {
            get
            {
                return this.FCUBS_BODYField;
            }
            set
            {
                this.FCUBS_BODYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.FCUBS_HEADER FCUBS_HEADER
        {
            get
            {
                return this.FCUBS_HEADERField;
            }
            set
            {
                this.FCUBS_HEADERField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FCUBS_BODY", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    public partial class FCUBS_BODY : object
    {
        
        private AccountService.LOGIN_INFO LOGIN_INFOField;
        
        private AccountService.SERVICE_IO SERVICE_IOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.LOGIN_INFO LOGIN_INFO
        {
            get
            {
                return this.LOGIN_INFOField;
            }
            set
            {
                this.LOGIN_INFOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.SERVICE_IO SERVICE_IO
        {
            get
            {
                return this.SERVICE_IOField;
            }
            set
            {
                this.SERVICE_IOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FCUBS_HEADER", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    public partial class FCUBS_HEADER : object
    {
        
        private string MSGIDField;
        
        private string OPERATIONField;
        
        private string PASSWORDField;
        
        private string REFERENCE_NOField;
        
        private string SERVICEField;
        
        private string USERIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MSGID
        {
            get
            {
                return this.MSGIDField;
            }
            set
            {
                this.MSGIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPERATION
        {
            get
            {
                return this.OPERATIONField;
            }
            set
            {
                this.OPERATIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD
        {
            get
            {
                return this.PASSWORDField;
            }
            set
            {
                this.PASSWORDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REFERENCE_NO
        {
            get
            {
                return this.REFERENCE_NOField;
            }
            set
            {
                this.REFERENCE_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERVICE
        {
            get
            {
                return this.SERVICEField;
            }
            set
            {
                this.SERVICEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERID
        {
            get
            {
                return this.USERIDField;
            }
            set
            {
                this.USERIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EXTERNALSERVICE_RES", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    public partial class EXTERNALSERVICE_RES : AccountService.EXTERNALSERVICE_REQ
    {
        
        private AccountService.FCUBS_ERROR_RESP FCUBS_ERROR_RESPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.FCUBS_ERROR_RESP FCUBS_ERROR_RESP
        {
            get
            {
                return this.FCUBS_ERROR_RESPField;
            }
            set
            {
                this.FCUBS_ERROR_RESPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LOGIN_INFO", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    public partial class LOGIN_INFO : object
    {
        
        private string APP_CODEField;
        
        private string PARAM2Field;
        
        private string PASSWORDField;
        
        private string USER_NAMEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APP_CODE
        {
            get
            {
                return this.APP_CODEField;
            }
            set
            {
                this.APP_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARAM2
        {
            get
            {
                return this.PARAM2Field;
            }
            set
            {
                this.PARAM2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD
        {
            get
            {
                return this.PASSWORDField;
            }
            set
            {
                this.PASSWORDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_NAME
        {
            get
            {
                return this.USER_NAMEField;
            }
            set
            {
                this.USER_NAMEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SERVICE_IO", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    public partial class SERVICE_IO : object
    {
        
        private string SERVICE_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERVICE_ID
        {
            get
            {
                return this.SERVICE_IDField;
            }
            set
            {
                this.SERVICE_IDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FCUBS_ERROR_RESP", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    public partial class FCUBS_ERROR_RESP : object
    {
        
        private AccountService.ERROR ERRORField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AccountService.ERROR ERROR
        {
            get
            {
                return this.ERRORField;
            }
            set
            {
                this.ERRORField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ERROR", Namespace="http://schemas.datacontract.org/2004/07/SampleSOAP.Models")]
    public partial class ERROR : object
    {
        
        private string ECODEField;
        
        private string EDESCField;
        
        private string REFDESCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECODE
        {
            get
            {
                return this.ECODEField;
            }
            set
            {
                this.ECODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDESC
        {
            get
            {
                return this.EDESCField;
            }
            set
            {
                this.EDESCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REFDESC
        {
            get
            {
                return this.REFDESCField;
            }
            set
            {
                this.REFDESCField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountService")]
    public interface IAccountService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetAccountDetails", ReplyAction="http://tempuri.org/IAccountService/GetAccountDetailsResponse")]
        AccountService.EXTERNALSERVICE_RES GetAccountDetails(AccountService.EXTERNALSERVICE_REQ eXTERNALSERVICE_REQ);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetAccountDetails", ReplyAction="http://tempuri.org/IAccountService/GetAccountDetailsResponse")]
        System.Threading.Tasks.Task<AccountService.EXTERNALSERVICE_RES> GetAccountDetailsAsync(AccountService.EXTERNALSERVICE_REQ eXTERNALSERVICE_REQ);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IAccountServiceChannel : AccountService.IAccountService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<AccountService.IAccountService>, AccountService.IAccountService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountServiceClient() : 
                base(AccountServiceClient.GetDefaultBinding(), AccountServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAccountService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountServiceClient.GetBindingForEndpoint(endpointConfiguration), AccountServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public AccountService.EXTERNALSERVICE_RES GetAccountDetails(AccountService.EXTERNALSERVICE_REQ eXTERNALSERVICE_REQ)
        {
            return base.Channel.GetAccountDetails(eXTERNALSERVICE_REQ);
        }
        
        public System.Threading.Tasks.Task<AccountService.EXTERNALSERVICE_RES> GetAccountDetailsAsync(AccountService.EXTERNALSERVICE_REQ eXTERNALSERVICE_REQ)
        {
            return base.Channel.GetAccountDetailsAsync(eXTERNALSERVICE_REQ);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8009/AccountService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AccountServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAccountService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AccountServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAccountService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAccountService,
        }
    }
}
